#!/usr/bin/python3
import time
import os
import sys

from post_ir_image import get_and_post_ir

def main_unit():
    while True:
        get_and_post_ir()
        time.sleep(1)

def daemonize():
    pid = os.fork()
    if pid > 0:
        pid_file = open('/var/run/ir-camera-client.pid','w')
        pid_file.write(str(pid)+"\n")
        pid_file.close()
        sys.exit()
    if pid == 0:
        main_unit()

if __name__ == '__main__':
    while True:
        daemonize()
